# Site settings
title: GitHub Test Blog
email: jurek.kedra@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog about IT, bikes, motobikes, electronics and so on.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jurek.kedra.org" # the base hostname & protocol for your site
twitter_username: jurked
github_username:  jkedra

# Build settings
markdown: kramdown

textile_ext: "textile,txtl,tl"
