# Site settings
title: Test Blog
email: jurek.kedra@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Testing blog about IT, bikes, motobikes, electronics and so on.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jurek.kedra.org" # the base hostname & protocol for your site
disqus: "testblog322"
twitter_username: jurked
github_username:  jkedra

collections:
  tests:
    output: true
  python:
    output: true
  climb:
    output: true

# Build settings
#markdown: kramdown

#textile_ext: "textile,txtl,tl"

